"""Reveal modal screen — shows compiled outputs after interview."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import Button, Static, TabbedContent, TabPane, TextArea

from writ_agents.compilers.agents_md import AgentsMdCompiler
from writ_agents.compilers.claude import ClaudeCompiler
from writ_agents.compilers.gemini import GeminiCompiler
from writ_agents.compilers.oas import OASCompiler
from writ_agents.compilers.openai import OpenAICompiler
from writ_agents.core.schema import ResolvedConnector, Spec

COMPILERS: dict[
    str,
    AgentsMdCompiler | ClaudeCompiler | OpenAICompiler | GeminiCompiler | OASCompiler,
] = {
    "AGENTS.md": AgentsMdCompiler(),
    "Claude": ClaudeCompiler(),
    "OpenAI": OpenAICompiler(),
    "Gemini": GeminiCompiler(),
    "OAS YAML": OASCompiler(),
}


class RevealScreen(Screen[None]):
    """Full-screen reveal showing compiled outputs."""

    BINDINGS = [("escape", "dismiss", "Back to interview")]

    def __init__(self, spec: Spec, connectors: list[ResolvedConnector]) -> None:
        super().__init__()
        self._spec = spec
        self._connectors = connectors

    def compose(self) -> ComposeResult:
        with Vertical():
            yield Static(f"# {self._spec.name}", markup=True, id="reveal-title")
            yield Static(self._spec.tagline, id="reveal-tagline")

            with TabbedContent():
                for tab_name, compiler in COMPILERS.items():
                    with TabPane(tab_name):
                        content = compiler.compile(self._spec, self._connectors)
                        lang = "markdown" if tab_name == "AGENTS.md" else "json"
                        yield TextArea(content, language=lang, read_only=True)

            with Horizontal(id="reveal-footer"):
                yield Button(
                    "\u2190 Back to interview", id="btn-back", variant="default"
                )
                yield Button(
                    "\u2b07 Download full bundle",
                    id="btn-download",
                    variant="primary",
                )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "btn-back":
            self.dismiss()
        elif event.button.id == "btn-download":
            self._download_bundle()

    def _download_bundle(self) -> None:
        """Write all 5 compiled formats to a local directory."""
        slug = self._spec.name.lower().replace(" ", "_")
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_dir = Path.home() / "writ_exports" / f"{slug}_{ts}"
        out_dir.mkdir(parents=True, exist_ok=True)

        ext_map: dict[str, tuple[str, str]] = {
            "AGENTS.md": ("AGENTS", ".md"),
            "Claude": ("claude", ".json"),
            "OpenAI": ("openai", ".json"),
            "Gemini": ("gemini", ".json"),
            "OAS YAML": ("oas", ".yaml"),
        }

        for tab_name, compiler in COMPILERS.items():
            fname, ext = ext_map[tab_name]
            content = compiler.compile(self._spec, self._connectors)
            (out_dir / f"{fname}{ext}").write_text(content, encoding="utf-8")

        # Write spec JSON
        (out_dir / "spec.json").write_text(
            json.dumps(self._spec.model_dump(), indent=2), encoding="utf-8"
        )

        # Write README
        readme = f"# {self._spec.name}\n\n{self._spec.tagline}\n\nGenerated by Writ.\n"
        (out_dir / "README.md").write_text(readme, encoding="utf-8")

        self.notify(f"Bundle saved to: {out_dir}", severity="information")
