"""Reveal modal screen — shows compiled outputs after interview."""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import Button, Static, TabbedContent, TabPane, TextArea

from writ_agents.compilers import COMPILERS
from writ_agents.core.schema import ResolvedConnector, Spec

# (display label, compiler key, file stem, extension, language for TextArea)
_TABS: list[tuple[str, str, str, str, str]] = [
    ("AGENTS.md", "agents-md", "AGENTS", ".md", "markdown"),
    ("Claude", "claude", "claude", ".json", "json"),
    ("OpenAI", "openai", "openai", ".json", "json"),
    ("Gemini", "gemini", "gemini", ".json", "json"),
    ("OAS YAML", "oas", "oas", ".yaml", "yaml"),
]


class RevealScreen(Screen[None]):
    """Full-screen reveal showing compiled outputs."""

    BINDINGS = [("escape", "dismiss", "Back to interview")]

    def __init__(self, spec: Spec, connectors: list[ResolvedConnector]) -> None:
        super().__init__()
        self._spec = spec
        self._connectors = connectors

    def compose(self) -> ComposeResult:
        with Vertical():
            yield Static(f"# {self._spec.name}", markup=True, id="reveal-title")
            yield Static(self._spec.tagline, id="reveal-tagline")

            with TabbedContent():
                for label, key, _stem, _ext, lang in _TABS:
                    with TabPane(label):
                        compiler = COMPILERS[key]
                        content = compiler.compile(self._spec, self._connectors)
                        yield TextArea(content, language=lang, read_only=True)

            with Horizontal(id="reveal-footer"):
                yield Button(
                    "\u2190 Back to interview", id="btn-back", variant="default"
                )
                yield Button(
                    "\u2b07 Download full bundle",
                    id="btn-download",
                    variant="primary",
                )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "btn-back":
            self.dismiss()
        elif event.button.id == "btn-download":
            self.run_worker(self._download_bundle(), exclusive=True)

    async def _download_bundle(self) -> None:
        """Write all compiled formats to a local directory (off the UI thread)."""
        slug = self._spec.name.lower().replace(" ", "_")
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_dir = Path.home() / "writ_exports" / f"{slug}_{ts}"

        files: list[tuple[str, str]] = []
        for _label, key, stem, ext, _lang in _TABS:
            compiler = COMPILERS[key]
            content = compiler.compile(self._spec, self._connectors)
            files.append((f"{stem}{ext}", content))
        files.append(("spec.json", json.dumps(self._spec.model_dump(), indent=2)))
        files.append(
            (
                "README.md",
                f"# {self._spec.name}\n\n{self._spec.tagline}\n\nGenerated by Writ.\n",
            )
        )

        def _write() -> None:
            # Write to a sibling tempdir, then atomic-rename into place so a
            # partial failure never leaves a half-written export directory.
            out_dir.parent.mkdir(parents=True, exist_ok=True)
            tmp = Path(tempfile.mkdtemp(prefix=f".{slug}_{ts}_", dir=out_dir.parent))
            try:
                for name, content in files:
                    (tmp / name).write_text(content, encoding="utf-8")
                os.replace(tmp, out_dir)
            except Exception:
                shutil.rmtree(tmp, ignore_errors=True)
                raise

        await asyncio.to_thread(_write)
        self.notify(f"Bundle saved to: {out_dir}", severity="information")
