"""AGENTS.md compiler — emits agentskills.io format."""

from __future__ import annotations

from writ_agents.core.schema import ResolvedConnector, Spec


class AgentsMdCompiler:
    format_name = "agents-md"
    file_extension = ".md"

    def compile(self, spec: Spec, connectors: list[ResolvedConnector]) -> str:
        lines = [
            f"# {spec.name}",
            f"> {spec.tagline}",
            "",
            f"**Archetype:** {spec.archetype}",
            "",
            "## Purpose",
            spec.purpose,
            "",
            "## Audience",
            spec.audience,
            "",
            "## Personality",
            ", ".join(spec.personality_traits),
            "",
            "## System Prompt",
            "```",
            spec.system_prompt,
            "```",
            "",
            "## Capabilities",
            "",
            "### Can do",
        ]
        for tool in spec.tools_needed:
            lines.append(f"- {tool}")
        lines += ["", "### Knows about"]
        for ks in spec.knowledge_sources:
            lines.append(f"- {ks}")
        if connectors:
            lines += ["", "## Connections Required"]
            for c in connectors:
                badge = c.source.upper()
                lines.append(f"- {c.icon} **{c.name}** `{badge}` — {c.description}")
        lines += ["", "## Guardrails"]
        for g in spec.guardrails:
            lines.append(f"- \u26d4 {g}")
        lines += [
            "",
            "## Oversight",
            spec.oversight.replace("_", " ").title(),
            "",
            "---",
            f"*Generated by [Writ](https://github.com/alberdarold/writ) v{spec.schema_version}*",
        ]
        return "\n".join(lines)
